allowBuilds:
  '@sentry/cli': set this to true or false
  core-js: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@stripe/react-stripe-js@6.7.0'
  - '@stripe/stripe-js@9.9.0'
